# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: A man, a plan, a blog.
email: carlryanoverton@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The coding blog of Carl Ryan Overton.  Javascript and chill?
baseurl: /blog # the subpath of your site, e.g. /blog
url: http://c-ro.github.io # the base hostname & protocol for your site
twitter_username: gnirtsmodnar
github_username:  c-ro

# Build settings
markdown: kramdown


